# Generated by Django 3.2 on 2021-04-17 11:19

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brigade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_brigade', models.IntegerField(verbose_name='Номер бригады')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('surname', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('patronomic', models.CharField(max_length=255, verbose_name='Отчество')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Номер телефона')),
            ],
        ),
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_model', models.CharField(max_length=255, verbose_name='Название детали')),
                ('count', models.IntegerField(verbose_name='Количество')),
                ('cost', models.IntegerField(verbose_name='Цена')),
                ('stock_availability', models.BooleanField(verbose_name='Наличие на складе')),
            ],
        ),
        migrations.CreateModel(
            name='List_equpment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_eq', models.CharField(max_length=255, verbose_name='Название оборудования')),
                ('count', models.IntegerField(verbose_name='Количество')),
                ('guarantee', models.BooleanField(verbose_name='Гарантия')),
            ],
        ),
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_prof', models.CharField(max_length=255, verbose_name='Название профессии')),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('surname', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('patronomic', models.CharField(max_length=255, verbose_name='Отчество')),
                ('pass_num', models.IntegerField(verbose_name='Номер пасспорта')),
                ('pass_ser', models.IntegerField(verbose_name='Серия пасспорта')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Номер телефона')),
                ('id_prof', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mainavto.profession', verbose_name='Название профессии')),
            ],
        ),
        migrations.CreateModel(
            name='Clientcar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_brand', models.CharField(max_length=255, verbose_name='Бренд автомобиля')),
                ('car_type', models.CharField(max_length=255, verbose_name='Тип автомобиля')),
                ('regist_num', models.IntegerField(verbose_name='Регистрационный номер')),
                ('police', models.BooleanField(verbose_name='Учёт в полиции')),
                ('id_client', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mainavto.client', verbose_name='Имя клиента')),
            ],
        ),
        migrations.CreateModel(
            name='Char_repaircar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='Описание работ')),
                ('id_brigade', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mainavto.brigade', verbose_name='Номер бригады')),
                ('id_clientcar', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mainavto.clientcar', verbose_name='Автомобиль клиента')),
            ],
        ),
        migrations.AddField(
            model_name='brigade',
            name='id_worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mainavto.worker', verbose_name='Имя рабочего'),
        ),
        migrations.CreateModel(
            name='Accountingwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='Описание работ')),
                ('id_clientcar', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mainavto.clientcar', verbose_name='Автомобиль клиента')),
                ('id_details', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mainavto.details', verbose_name='Деталь для автомобиля')),
            ],
        ),
    ]
