# Generated by Django 3.2 on 2021-04-17 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainavto', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиенты'},
        ),
        migrations.AlterModelOptions(
            name='clientcar',
            options={'verbose_name': 'Автомобиль клиента', 'verbose_name_plural': 'Автомобили клиентов'},
        ),
        migrations.AlterModelOptions(
            name='profession',
            options={'verbose_name': 'Профессии рабочих', 'verbose_name_plural': 'Профессии рабочих'},
        ),
    ]
