# Generated by Django 3.2 on 2021-04-21 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainavto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreateBrigade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_brigade', models.IntegerField(max_length=6, verbose_name='Номер бригады')),
            ],
            options={
                'verbose_name': 'Создание номера бригады',
                'verbose_name_plural': 'Создание номера бригады',
            },
        ),
        migrations.CreateModel(
            name='Listwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_listwork', models.CharField(max_length=255, verbose_name='Название услуги')),
                ('cost_listwork', models.IntegerField(null=True, verbose_name='Цена услуги')),
            ],
            options={
                'verbose_name': 'Лист услуг',
                'verbose_name_plural': 'Предоставляемые услуги',
            },
        ),
        migrations.AlterModelOptions(
            name='accountingwork',
            options={'verbose_name': 'Учет работ', 'verbose_name_plural': 'Учет работ'},
        ),
        migrations.AlterModelOptions(
            name='brigade',
            options={'verbose_name': 'Бригада', 'verbose_name_plural': 'Бригады'},
        ),
        migrations.AlterModelOptions(
            name='char_repaircar',
            options={'verbose_name': 'График работы', 'verbose_name_plural': 'График работ'},
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиенты'},
        ),
        migrations.AlterModelOptions(
            name='clientcar',
            options={'verbose_name': 'Автомобиль клиента', 'verbose_name_plural': 'Автомобили клиентов'},
        ),
        migrations.AlterModelOptions(
            name='details',
            options={'verbose_name': 'Детали', 'verbose_name_plural': 'Детали'},
        ),
        migrations.AlterModelOptions(
            name='list_equpment',
            options={'verbose_name': 'Список оборудования', 'verbose_name_plural': 'Список оборудования'},
        ),
        migrations.AlterModelOptions(
            name='profession',
            options={'verbose_name': 'Профессии рабочих', 'verbose_name_plural': 'Профессии рабочих'},
        ),
        migrations.AlterModelOptions(
            name='worker',
            options={'verbose_name': 'Рабочий', 'verbose_name_plural': 'Рабочие'},
        ),
        migrations.RemoveField(
            model_name='brigade',
            name='num_brigade',
        ),
        migrations.AddField(
            model_name='accountingwork',
            name='total_cost',
            field=models.IntegerField(blank=True, null=True, verbose_name='Итоговая цена'),
        ),
        migrations.AddField(
            model_name='char_repaircar',
            name='datatime',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Время работы'),
        ),
        migrations.AddField(
            model_name='details',
            name='stock_onzakaz',
            field=models.BooleanField(null=True, verbose_name='Нуждаеться в заказе'),
        ),
        migrations.AlterField(
            model_name='accountingwork',
            name='id_details',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mainavto.details', verbose_name='Деталь из скалада'),
        ),
        migrations.AlterField(
            model_name='clientcar',
            name='regist_num',
            field=models.IntegerField(max_length=9, verbose_name='Регистрационный номер'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='pass_num',
            field=models.IntegerField(max_length=6, verbose_name='Номер пасспорта'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='pass_ser',
            field=models.IntegerField(max_length=4, verbose_name='Серия пасспорта'),
        ),
        migrations.CreateModel(
            name='Zakazdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=255, verbose_name='Название детали')),
                ('count', models.IntegerField(verbose_name='Количество')),
                ('cost_det', models.IntegerField(verbose_name='Цена')),
                ('stock_zakaz', models.BooleanField(null=True, verbose_name='Привезли на склад')),
                ('id_clientcar', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mainavto.clientcar', verbose_name='Автомобиль клиента')),
            ],
            options={
                'verbose_name': 'Заказ деталей',
                'verbose_name_plural': 'Заказ деталей',
            },
        ),
        migrations.AddField(
            model_name='accountingwork',
            name='id_listwork',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mainavto.listwork', verbose_name='Название услуги'),
        ),
        migrations.AddField(
            model_name='brigade',
            name='id_brigade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mainavto.createbrigade', verbose_name='Номер бригады'),
        ),
    ]
