# Generated by Django 3.2 on 2021-04-28 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainavto', '0002_auto_20210421_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='zakazdetails',
            name='total_zak',
            field=models.IntegerField(blank=True, null=True, verbose_name='Итоговая цена закупку'),
        ),
        migrations.AlterField(
            model_name='accountingwork',
            name='id_details',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mainavto.details', verbose_name='Деталь'),
        ),
    ]
