# Generated by Django 3.2 on 2021-04-17 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainavto', '0002_auto_20210417_1636'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accountingwork',
            options={'verbose_name': 'Учет работ', 'verbose_name_plural': 'Учет работ'},
        ),
        migrations.AlterModelOptions(
            name='brigade',
            options={'verbose_name': 'Бригада', 'verbose_name_plural': 'Бригады'},
        ),
        migrations.AlterModelOptions(
            name='char_repaircar',
            options={'verbose_name': 'График работы', 'verbose_name_plural': 'График работ'},
        ),
        migrations.AlterModelOptions(
            name='details',
            options={'verbose_name': 'Детали', 'verbose_name_plural': 'Детали'},
        ),
        migrations.AlterModelOptions(
            name='list_equpment',
            options={'verbose_name': 'Список оборудования', 'verbose_name_plural': 'Список оборудования'},
        ),
        migrations.AlterModelOptions(
            name='worker',
            options={'verbose_name': 'Рабочий', 'verbose_name_plural': 'Рабочие'},
        ),
        migrations.AlterField(
            model_name='brigade',
            name='num_brigade',
            field=models.IntegerField(max_length=6, verbose_name='Номер бригады'),
        ),
        migrations.AlterField(
            model_name='clientcar',
            name='regist_num',
            field=models.IntegerField(max_length=9, verbose_name='Регистрационный номер'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='pass_num',
            field=models.IntegerField(max_length=6, verbose_name='Номер пасспорта'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='pass_ser',
            field=models.IntegerField(max_length=4, verbose_name='Серия пасспорта'),
        ),
    ]
