# Generated by Django 3.2 on 2021-04-18 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainavto', '0004_char_repaircar_datatime'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreateBrigade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_brigade', models.IntegerField(max_length=6, verbose_name='Номер бригады')),
            ],
            options={
                'verbose_name': 'Создание номера бригады',
                'verbose_name_plural': 'Создание номера бригады',
            },
        ),
        migrations.CreateModel(
            name='Listwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_listwork', models.CharField(max_length=255, verbose_name='Название услуги')),
            ],
            options={
                'verbose_name': 'Лист услуг',
                'verbose_name_plural': 'Предоставляемые услуги',
            },
        ),
        migrations.RemoveField(
            model_name='brigade',
            name='num_brigade',
        ),
        migrations.AddField(
            model_name='brigade',
            name='id_brigade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mainavto.createbrigade', verbose_name='Номер бригады'),
        ),
    ]
