# Generated by Django 3.2 on 2021-04-18 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainavto', '0005_auto_20210418_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountingwork',
            name='id_listwork',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mainavto.listwork', verbose_name='Название услуги'),
        ),
    ]
